version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    working_directory: ~/ingresse/js-sdk
    parallelism: 1
    shell: /bin/bash --login

    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      COVERALLS_SERVICE_NAME: circleci
      COVERALLS_REPO_TOKEN: u8Ftj6YdfstIAQAUlqYHuJdW7BDqiqQa2
      COVERALLS_GIT_COMMIT: $CIRCLE_SHA1
      COVERALLS_GIT_BRANCH: $CIRCLE_BRANCH

    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master

    - run: npm install
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules

    - run: npm install coveralls -g
    - run: npm test
    - run: cat ./coverage/lcov.info | coveralls || { echo 'Coveralls error'; exit 0; }

    - store_test_results:
        path: /tmp/circleci-test-results

    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: ./coverage
    - store_artifacts:
        path: /tmp/circleci-test-results
